-- Enable pgcrypto for password hashing
create extension if not exists pgcrypto;

-- 0. Missing Tables Reconstruction
-- Profiles
create table if not exists public.profiles (
    id uuid references auth.users(id) on delete cascade primary key,
    full_name text,
    email text,
    role text default 'client',
    avatar_url text,
    updated_at timestamp with time zone
);

-- Exercises
create table if not exists public.exercises (
    id uuid default gen_random_uuid() primary key,
    name text not null,
    muscle_group text,
    category text,
    video_url text,
    created_by uuid references auth.users(id) on delete set null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Workouts
create table if not exists public.workouts (
    id uuid default gen_random_uuid() primary key,
    user_id uuid references public.profiles(id) on delete cascade not null,
    name text not null,
    date timestamp with time zone default timezone('utc'::text, now()) not null,
    status text default 'draft', -- draft, completed
    feedback_notes text,
    client_read_at timestamp with time zone,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Workout Blocks
create table if not exists public.workout_blocks (
    id uuid default gen_random_uuid() primary key,
    workout_id uuid references public.workouts(id) on delete cascade not null,
    order_index integer not null,
    type text default 'single',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Block Exercises
create table if not exists public.block_exercises (
    id uuid default gen_random_uuid() primary key,
    block_id uuid references public.workout_blocks(id) on delete cascade not null,
    exercise_id uuid references public.exercises(id) on delete set null,
    custom_exercise_name text, -- fallback if ad-hoc
    position text default 'A',
    notes text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Sets
create table if not exists public.sets (
    id uuid default gen_random_uuid() primary key,
    block_exercise_id uuid references public.block_exercises(id) on delete cascade not null,
    round_index integer not null,
    weight numeric,
    reps numeric,
    rpe numeric,
    rest_seconds numeric,
    tempo text,
    completed boolean default false,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Trainer Clients
create table if not exists public.trainer_clients (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    trainer_id uuid references public.profiles(id) on delete cascade not null,
    client_id uuid references public.profiles(id) on delete cascade not null,
    unique(trainer_id, client_id)
);

-- 1. Trigger Function: handle_new_user
-- Ensures every new user in auth.users gets a matching profile in public.profiles
drop function if exists public.handle_new_user() cascade;
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, email, role)
  values (
    new.id,
    new.raw_user_meta_data->>'full_name',
    new.email,
    coalesce(new.raw_user_meta_data->>'role', 'client')
  );
  return new;
end;
$$;

-- 2. Trigger Definition
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 3. RPC: create_client_as_trainer
-- Allows a trainer to create a new client user + link them in trainer_clients
create or replace function public.create_client_as_trainer(
  p_email text,
  p_full_name text
)
returns uuid
language plpgsql
security definer
as $$
declare
  new_user_id uuid;
begin
  -- Insert into auth.users with auto-confirmation
  insert into auth.users (
    instance_id,
    id,
    aud,
    role,
    email,
    encrypted_password,
    email_confirmed_at,
    raw_app_meta_data,
    raw_user_meta_data,
    created_at,
    updated_at,
    confirmation_token,
    email_change,
    email_change_token_new,
    recovery_token
  ) values (
    '00000000-0000-0000-0000-000000000000',
    gen_random_uuid(),
    'authenticated',
    'authenticated',
    p_email,
    crypt('IronTrack2025', gen_salt('bf')), -- Default Password
    now(), -- Confirmed immediately
    '{"provider": "email", "providers": ["email"]}',
    jsonb_build_object('full_name', p_full_name, 'role', 'client'),
    now(),
    now(),
    '',
    '',
    '',
    ''
  ) returning id into new_user_id;

  -- Link to the trainer who called this function
  insert into public.trainer_clients (trainer_id, client_id)
  values (auth.uid(), new_user_id);

  return new_user_id;
end;
$$;

-- 4. RPC: delete_client_completely
-- Hard delete a user (Cascades should handle profile/relations if configured, otherwise might need manual cleanup)
create or replace function public.delete_client_completely(p_client_id uuid)
returns void
language plpgsql
security definer
as $$
begin
  delete from auth.users where id = p_client_id;
end;
$$;
