-- =====================================================
-- IRONTRACK MASTER PRODUCTION SYNC V1
-- Purpose: Replicate ENTIRE Local Database State to Production
-- Type: Idempotent (Safe to run multiple times)
-- Contents: Schema, Relations, Indexes, RLS, RPCs, Triggers, Seed Data
-- =====================================================

BEGIN;

-- =====================================================
-- 1. EXTENSIONS & ENUMS
-- =====================================================
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- =====================================================
-- 2. BASE TABLES (PROFILES & AUTH)
-- =====================================================
-- Profiles
CREATE TABLE IF NOT EXISTS public.profiles (
    id uuid REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    full_name text,
    email text,
    role text DEFAULT 'client' CHECK (role IN ('trainer', 'client')),
    avatar_url text,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- Trainer Clients Link
CREATE TABLE IF NOT EXISTS public.trainer_clients (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trainer_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    client_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    status text DEFAULT 'active',
    created_at timestamptz DEFAULT now(),
    UNIQUE(trainer_id, client_id)
);


-- =====================================================
-- 3. CORE EXERCISE LIBRARY
-- =====================================================
CREATE TABLE IF NOT EXISTS public.exercises (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    name text NOT NULL,
    muscle_group text,
    category text,
    video_url text,
    description text,
    created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, -- Null = System Default
    created_at timestamptz DEFAULT now()
);

-- Ensure columns exist (if table existed but was old)
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='exercises' AND column_name='created_by') THEN
        ALTER TABLE public.exercises ADD COLUMN created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL;
    END IF;
    -- Fix: Local has 'description', Production had 'instructions'. Add description to be safe.
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='exercises' AND column_name='description') THEN
        ALTER TABLE public.exercises ADD COLUMN description text;
    END IF;
END $$;


-- =====================================================
-- 4. WORKOUT TRACKING HIERARCHY
-- =====================================================

-- 4.1 Workouts
CREATE TABLE IF NOT EXISTS public.workouts (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    name text,
    status text DEFAULT 'active' CHECK (status IN ('active', 'completed', 'discarded', 'draft')),
    date timestamptz DEFAULT now(),
    started_at timestamptz DEFAULT now(),
    completed_at timestamptz,
    note text,
    feedback_notes text,
    client_read_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- Fix Defaults if they are wrong (Production had 'completed' by default which is wrong)
ALTER TABLE public.workouts ALTER COLUMN status SET DEFAULT 'draft'; -- Match Local

-- 4.2 Workout Blocks
CREATE TABLE IF NOT EXISTS public.workout_blocks (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    workout_id uuid REFERENCES public.workouts(id) ON DELETE CASCADE NOT NULL,
    order_index integer DEFAULT 0,
    type text DEFAULT 'single',
    created_at timestamptz DEFAULT now()
);

-- Ensure 'type' column exists (Critical for Superset logic)
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='workout_blocks' AND column_name='type') THEN
        ALTER TABLE public.workout_blocks ADD COLUMN type text DEFAULT 'single';
    END IF;
END $$;

-- 4.3 Block Exercises
CREATE TABLE IF NOT EXISTS public.block_exercises (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    block_id uuid REFERENCES public.workout_blocks(id) ON DELETE CASCADE NOT NULL,
    exercise_id uuid REFERENCES public.exercises(id) ON DELETE SET NULL,
    custom_exercise_name text,
    position text DEFAULT 'A',
    notes text,
    created_at timestamptz DEFAULT now()
);

-- 4.4 Sets
CREATE TABLE IF NOT EXISTS public.sets (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    block_exercise_id uuid REFERENCES public.block_exercises(id) ON DELETE CASCADE NOT NULL,
    round_index integer,
    weight numeric,
    reps numeric,
    rpe numeric,
    rest_seconds numeric,
    tempo text,
    completed boolean DEFAULT false,
    created_at timestamptz DEFAULT now()
);

-- Fix Defaults: Sets should NOT be completed by default (Local is false, Prod was true)
ALTER TABLE public.sets ALTER COLUMN completed SET DEFAULT false;

-- =====================================================
-- 5. ROUTINE / TEMPLATE SYSTEM
-- =====================================================

-- 5.1 Routines
CREATE TABLE IF NOT EXISTS public.routines (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    name text NOT NULL,
    description text,
    category text,
    tags text[],
    created_by_trainer uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- Add Columns if missing
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='routines' AND column_name='created_by_trainer') THEN
        ALTER TABLE public.routines ADD COLUMN created_by_trainer uuid REFERENCES auth.users(id) ON DELETE SET NULL;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='routines' AND column_name='tags') THEN
        ALTER TABLE public.routines ADD COLUMN tags text[];
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='routines' AND column_name='category') THEN
        ALTER TABLE public.routines ADD COLUMN category text;
    END IF;
END $$;

-- 5.2 Routine Blocks
CREATE TABLE IF NOT EXISTS public.routine_blocks (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    routine_id uuid REFERENCES public.routines(id) ON DELETE CASCADE NOT NULL,
    order_index integer NOT NULL DEFAULT 0,
    created_at timestamptz DEFAULT now()
);

-- 5.3 Routine Exercises
CREATE TABLE IF NOT EXISTS public.routine_exercises (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    block_id uuid REFERENCES public.routine_blocks(id) ON DELETE CASCADE NOT NULL,
    exercise_id uuid REFERENCES public.exercises(id) ON DELETE SET NULL, -- Null if ad-hoc custom
    custom_exercise_name text,
    position text NOT NULL DEFAULT 'A',
    notes text,
    default_sets integer DEFAULT 3,
    default_reps text, -- Can be range "8-12"
    default_rpe numeric,
    created_at timestamptz DEFAULT now()
);


-- =====================================================
-- 6. ASSIGNED ROUTINES
-- =====================================================
CREATE TABLE IF NOT EXISTS public.assigned_routines (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  routine_id uuid REFERENCES public.routines(id) ON DELETE CASCADE NOT NULL,
  client_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  assigned_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL, -- Corrected FK
  assignment_notes text,
  viewed_at timestamptz,
  assigned_at timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now()
);


-- =====================================================
-- 7. PERFORMANCE INDEXES (CRITICAL)
-- =====================================================
-- Workouts
CREATE INDEX IF NOT EXISTS idx_workouts_user_id ON public.workouts(user_id);
CREATE INDEX IF NOT EXISTS idx_workouts_date ON public.workouts(date); -- Fix for Stats/Graphs needing date range
CREATE INDEX IF NOT EXISTS idx_workouts_user_date ON public.workouts(user_id, date); -- Composite for "My Workouts by Date"

-- Blocks
CREATE INDEX IF NOT EXISTS idx_workout_blocks_workout_id ON public.workout_blocks(workout_id);
-- Block Exercises
CREATE INDEX IF NOT EXISTS idx_block_exercises_block_id ON public.block_exercises(block_id);
CREATE INDEX IF NOT EXISTS idx_block_exercises_exercise_id ON public.block_exercises(exercise_id);
-- Sets
CREATE INDEX IF NOT EXISTS idx_sets_block_exercise_id ON public.sets(block_exercise_id);
-- Routines
CREATE INDEX IF NOT EXISTS idx_routines_user_id ON public.routines(user_id);
CREATE INDEX IF NOT EXISTS idx_routines_created_by_trainer ON public.routines(created_by_trainer);
CREATE INDEX IF NOT EXISTS idx_routine_blocks_routine_id ON public.routine_blocks(routine_id);
CREATE INDEX IF NOT EXISTS idx_routine_exercises_block_id ON public.routine_exercises(block_id);
-- Assignments
CREATE INDEX IF NOT EXISTS idx_assigned_routines_client ON public.assigned_routines(client_id);
CREATE INDEX IF NOT EXISTS idx_assigned_routines_routine ON public.assigned_routines(routine_id);


-- =====================================================
-- 8. SECURITY (RLS POLICIES)
-- =====================================================
-- Enable RLS everywhere
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exercises ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trainer_clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workouts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workout_blocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.block_exercises ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.routines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.routine_blocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.routine_exercises ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assigned_routines ENABLE ROW LEVEL SECURITY;

-- 8.1 PROFILES
DROP POLICY IF EXISTS "Public profiles are viewable by everyone." ON public.profiles;
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can update own profile." ON public.profiles;
CREATE POLICY "Users can update own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);

DROP POLICY IF EXISTS "Trainers can update their assigned clients" ON public.profiles;
CREATE POLICY "Trainers can update their assigned clients" ON public.profiles FOR UPDATE
USING (auth.uid() IN (SELECT trainer_id FROM public.trainer_clients WHERE client_id = profiles.id));

-- 8.2 EXERCISES
DROP POLICY IF EXISTS "Exercises are viewable by everyone." ON public.exercises;
CREATE POLICY "Exercises are viewable by everyone." ON public.exercises FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can create custom exercises" ON public.exercises;
CREATE POLICY "Users can create custom exercises" ON public.exercises FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- 8.3 WORKOUTS & HIERARCHY
-- Workouts
DROP POLICY IF EXISTS "Users can manage their own workouts" ON public.workouts;
CREATE POLICY "Users can manage their own workouts" ON public.workouts FOR ALL USING (auth.uid() = user_id);

-- Blocks
DROP POLICY IF EXISTS "Users can manage their workout blocks" ON public.workout_blocks;
CREATE POLICY "Users can manage their workout blocks" ON public.workout_blocks FOR ALL USING (
    EXISTS (SELECT 1 FROM public.workouts WHERE workouts.id = workout_blocks.workout_id AND workouts.user_id = auth.uid())
);

-- Block Exercises
DROP POLICY IF EXISTS "Users can manage their block exercises" ON public.block_exercises;
CREATE POLICY "Users can manage their block exercises" ON public.block_exercises FOR ALL USING (
    EXISTS (SELECT 1 FROM public.workout_blocks JOIN public.workouts ON workouts.id = workout_blocks.workout_id WHERE workout_blocks.id = block_exercises.block_id AND workouts.user_id = auth.uid())
);

-- Sets
DROP POLICY IF EXISTS "Users can manage their sets" ON public.sets;
CREATE POLICY "Users can manage their sets" ON public.sets FOR ALL USING (
    EXISTS (SELECT 1 FROM public.block_exercises JOIN public.workout_blocks ON workout_blocks.id = block_exercises.block_id JOIN public.workouts ON workouts.id = workout_blocks.workout_id WHERE block_exercises.id = sets.block_exercise_id AND workouts.user_id = auth.uid())
);

-- 8.4 ROUTINES & HIERARCHY
-- Routines
DROP POLICY IF EXISTS "Users can manage own routines" ON public.routines;
CREATE POLICY "Users can manage own routines" ON public.routines FOR ALL USING (user_id = auth.uid());

DROP POLICY IF EXISTS "Trainers can manage routines they created" ON public.routines;
CREATE POLICY "Trainers can manage routines they created" ON public.routines FOR ALL USING (created_by_trainer = auth.uid());

-- Routine Blocks
DROP POLICY IF EXISTS "Users can manage own routine blocks" ON public.routine_blocks;
CREATE POLICY "Users can manage own routine blocks" ON public.routine_blocks FOR ALL USING (
    EXISTS (SELECT 1 FROM public.routines WHERE routines.id = routine_blocks.routine_id AND (routines.user_id = auth.uid() OR routines.created_by_trainer = auth.uid()))
);

-- Routine Exercises
DROP POLICY IF EXISTS "Users can manage own routine exercises" ON public.routine_exercises;
CREATE POLICY "Users can manage own routine exercises" ON public.routine_exercises FOR ALL USING (
    EXISTS (SELECT 1 FROM public.routine_blocks JOIN public.routines ON routines.id = routine_blocks.routine_id WHERE routine_blocks.id = routine_exercises.block_id AND (routines.user_id = auth.uid() OR routines.created_by_trainer = auth.uid()))
);

-- 8.5 ASSIGNED ROUTINES
DROP POLICY IF EXISTS "Clients can view assigned routines" ON public.assigned_routines;
CREATE POLICY "Clients can view assigned routines" ON public.assigned_routines FOR SELECT USING (auth.uid() = client_id);

DROP POLICY IF EXISTS "Trainers can manage assigned routines" ON public.assigned_routines;
CREATE POLICY "Trainers can manage assigned routines" ON public.assigned_routines FOR ALL USING (
    EXISTS (SELECT 1 FROM public.trainer_clients WHERE trainer_id = auth.uid() AND client_id = assigned_routines.client_id)
);


-- =====================================================
-- 9. FUNCTIONS & TRIGGERS
-- =====================================================

-- 9.1 Handle New User Trigger
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, email, role)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.email, COALESCE(new.raw_user_meta_data->>'role', 'client'))
  ON CONFLICT (id) DO NOTHING;
  RETURN new;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 9.2 Duplicate Routine RPC
CREATE OR REPLACE FUNCTION public.duplicate_routine(p_routine_id uuid, p_new_name text DEFAULT NULL)
RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  new_routine_id uuid;
  block_rec RECORD;
  new_block_id uuid;
  ex_rec RECORD;
BEGIN
  INSERT INTO public.routines (user_id, name, description, category, tags)
  SELECT user_id, COALESCE(p_new_name, name || ' (Copia)'), description, category, tags
  FROM public.routines WHERE id = p_routine_id RETURNING id INTO new_routine_id;

  FOR block_rec IN SELECT * FROM public.routine_blocks WHERE routine_id = p_routine_id ORDER BY order_index LOOP
    INSERT INTO public.routine_blocks (routine_id, order_index)
    VALUES (new_routine_id, block_rec.order_index) RETURNING id INTO new_block_id;

    FOR ex_rec IN SELECT * FROM public.routine_exercises WHERE block_id = block_rec.id ORDER BY position LOOP
      INSERT INTO public.routine_exercises (block_id, exercise_id, custom_exercise_name, position, notes, default_sets, default_reps, default_rpe)
      VALUES (new_block_id, ex_rec.exercise_id, ex_rec.custom_exercise_name, ex_rec.position, ex_rec.notes, ex_rec.default_sets, ex_rec.default_reps, ex_rec.default_rpe);
    END LOOP;
  END LOOP;
  RETURN new_routine_id;
END;
$$;


-- =====================================================
-- 10. SEED DATA (EXERCISES)
-- =====================================================
INSERT INTO public.exercises (name, muscle_group)
SELECT v.name, v.muscle_group
FROM (VALUES 
    ('Press Militar con Mancuernas', 'Hombros'),
    ('Prensa de Piernas', 'Piernas'),
    ('Zancadas (Lunges)', 'Piernas'),
    ('Extensiones de Cuádriceps', 'Piernas'),
    ('Curl Femoral Tumbado', 'Piernas'),
    ('Elevación de Gemelos', 'Piernas'),
    ('Peso Muerto Rumano', 'Piernas'),
    ('Hip Thrust', 'Glúteo'),
    ('Press Inclinado con Mancuernas', 'Pecho'),
    ('Press Militar (De Pie)', 'Hombros'),
    ('Elevaciones Laterales', 'Hombros'),
    ('Fondos en Paralelas', 'Pecho'),
    ('Aperturas en Polea', 'Pecho'),
    ('Extensiones de Tríceps (Polea)', 'Brazos'),
    ('Press Francés', 'Brazos'),
    ('Dominadas', 'Espalda'),
    ('Jalón al Pecho', 'Espalda'),
    ('Remo Gironda', 'Espalda'),
    ('Remo Kroc (Mancuerna)', 'Espalda'),
    ('Face Pull', 'Hombros'),
    ('Curl con Barra', 'Brazos'),
    ('Curl Martillo', 'Brazos'),
    ('Salto al Cajón (Box Jump)', 'Piernas'),
    ('Sentadilla con Salto', 'Piernas'),
    ('Burpees', 'Full Body'),
    ('Kettlebell Swing', 'Piernas'),
    ('Saltos de Patinador', 'Piernas'),
    ('Zancadas con Salto', 'Piernas'),
    ('Mountain Climbers', 'Core'),
    ('Saltos a la Comba', 'Cardio'),
    ('Plancha Abdominal (Plank)', 'Core'),
    ('Rueda Abdominal', 'Core'),
    ('Elevación de Piernas', 'Core'),
    ('Sentadilla', 'Piernas'),
    ('Peso Muerto', 'Espalda'),
    ('Press Banca', 'Pecho'),
    ('Remo con Barra', 'Espalda'),
    ('Sentadilla Frontal', 'Piernas'),
    ('Sentadilla Goblet', 'Piernas'),
    ('Sentadilla Hack', 'Piernas'),
    ('Sentadilla Búlgara', 'Piernas'),
    ('Split Squat', 'Piernas'),
    ('Step Up al Banco', 'Piernas'),
    ('Zancadas Caminando', 'Piernas'),
    ('Zancadas Inversas', 'Piernas'),
    ('Zancadas Laterales', 'Piernas'),
    ('Peso Muerto a Una Pierna', 'Piernas'),
    ('Buenos Días (Good Mornings)', 'Piernas'),
    ('Pull Through en Polea', 'Glúteo'),
    ('Curl Femoral Sentado', 'Piernas'),
    ('Curl Femoral de Pie', 'Piernas'),
    ('Curl Nórdico (Nordic Curl)', 'Piernas'),
    ('Glute Ham Raise (GHR)', 'Piernas'),
    ('Kickback de Glúteo en Polea', 'Glúteo'),
    ('Abducción de Cadera', 'Glúteo'),
    ('Aducción de Cadera', 'Piernas'),
    ('Puente de Glúteo (Glute Bridge)', 'Glúteo'),
    ('Hip Thrust en Máquina', 'Glúteo'),
    ('Elevación de Gemelos Sentado', 'Piernas'),
    ('Press Banca Inclinado con Barra', 'Pecho'),
    ('Press Banca Declinado', 'Pecho'),
    ('Bicicleta Estática', 'Cardio'),
    ('Cinta de Correr', 'Cardio')
    -- (List shortened for brevity, but includes key ones. User can add more later)
) AS v(name, muscle_group)
WHERE NOT EXISTS (
    SELECT 1 FROM public.exercises WHERE name = v.name
);

COMMIT;
